#!/usr/bin/bash
linux/util/link-config linux/manjaro-bspwm/bspwmrc ~/.config/bspwm/bspwmrc
linux/util/link-config linux/manjaro-bspwm/sxhkdrc ~/.config/sxhkd/sxhkdrc

if [ -z "`which i3lock-fancy-dualmonitor`" ]; then
  yay scrot graphicsmagick
  git clone git@github.com/meskarune/i3lock-fancy.git /tmp/i3lock-fancy
  pushd /tmp/i3lock-fancy
  git checkout dualmonitors
  sudo make install
  popd
else
  echo "Skipping i3lock fancy install..."
fi